<?php

/**
 * @phan-file-suppress PhanUnreferencedConstant
 */

declare(strict_types=1);

namespace EricFortmeyer\ActivityLog\DI\Tokens;

const ACTIVITY_LOG_APP_PASSWD_KEY = "ACTIVITY_LOG_APP_PASSWD_KEY";
const ACTIVITY_LOG_CACHE_ENABLED = "ACTIVITY_LOG_CACHE_ENABLED";
const ACTIVITY_LOG_DATABASE = "ACTIVITY_LOG_DATABASE";
const ACTIVITY_LOG_HOST = "ACTIVITY_LOG_HOST";
const ACTIVITY_STORE_DATABASE = "ACTIVITY_STORE_DATABASE";
const ACTIVITY_STORE_HOST = "ACTIVITY_STORE_HOST";
const ACTIVITY_STORE_USER = "ACTIVITY_STORE_USER";
const APP_CONFIG_DB_FILENAME = "APP_CONFIG_DB_FILENAME";
const APP_CONFIG_STORAGE = "APP_CONFIG_STORAGE";
const APP_CONFIG_TABLE_NAME = "APP_CONFIG_TABLE_NAME";
const APP_CONFIG_DB_CONNECTION = "APP_CONFIG_DB_CONNECTION";
const APP_DB_CONNECTION = "APP_DB_CONNECTION";
const AUTH_CLIENT_ID = "AUTH_CLIENT_ID";
const AUTH_CLIENT_SECRET = "AUTH_CLIENT_SECRET";
const AUTH_COOKIE_SECRET = "AUTH_COOKIE_SECRET";
const AUTH_DOMAIN = "AUTH_DOMAIN";
const BOOTSTRAPPER = "BOOTSTRAPPER";
const CALLBACK_MIDDLEWARE = "CALLBACK_MIDDLEWARE";
const CREDIT_HOURS_STORAGE = "CREDIT_HOURS_STORAGE";
const DATA_DIR = "DATA_DIR";
const LOGIN_MIDDLEWARE = "LOGIN_MIDDLEWARE";
const LOGIN_PASSWD_FILENAME = "LOGIN_PASSWD_FILENAME";
const LOGOUT_MIDDLEWARE = "LOGOUT_MIDDLEWARE";
const MIGRATION_RUNNER_DB_CONNECTION = "MIGRATION_RUNNER_DB_CONNECTION";
const MIGRATION_RUNNER_USER = "ACTIVITY_STORE_MIGRATION_RUNNER_USER";
const REMARKS_STORAGE = "REMARKS_STORAGE";
const SECRETS_APP_KEY = "SECRETS_APP_KEY";
const SECRETS_APP_PATH = "SECRETS_APP_PATH";
const SECRETS_CLIENT = "SECRETS_CLIENT";
const SECRETS_DIR = "SECRETS_DIR";
const SECRETS_LOGIN_KEY = "SECRETS_LOGIN_KEY";
const SECRETS_LOGIN_PATH = "SECRETS_LOGIN_PATH";
const SECRETS_SERVICE_HOST = "SECRETS_SERVICE_HOST";
const SECRETS_SERVICE_PORT = "SECRETS_SERVICE_PORT";
const SECRETS_TOKEN_TTL = "SECRETS_TOKEN_TTL";
const SECRETS_VALUE_TTL = "SECRETS_VALUE_TTL";
const TIME_ENTRY_STORAGE = "TIME_ENTRY_STORAGE";
