<?php

declare(strict_types=1);

use EricFortmeyer\ActivityLog\TimeEntry;
use EricFortmeyer\ActivityLog\UserInterface\Contexts\TimeEntriesContext;
use Phpolar\Model\InputTypes;

use function EricFortmeyer\ActivityLog\UserInterface\Components\formInput;
use function EricFortmeyer\ActivityLog\UserInterface\Components\timeEntriesNav;
use function EricFortmeyer\ActivityLog\UserInterface\HTMLElements\head;

(function (TimeEntriesContext $view) {
?>
    <!DOCTYPE html>
    <html lang="en">
    <?= head(
        ctx: $view,
        dialogScript: <<<HTML
        <script defer src="/resources/js/dialog-handlers.js"></script>
        HTML
    )
    ?>

    <body>
        <header>
            <div class="container">
                <nav>
                    <ul>
                        <li>
                            <h1>
                                <span>&#9889;</span>
                                <?= $view->title ?>
                            </h1>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="#" id="profile-dialog-open-button">
                                <img
                                    src="<?= $view->user->picture  ?>"
                                    alt="Avatar of <?= $view->user->name ?>"
                                    width="48"
                                    height="48"
                                    data-style="avatar">
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>
        <main class="container">
            <?= timeEntriesNav($view) ?>
            <div class=grid>
                <article id="activities">
                    <h2>&#x1F4C5; <?= $view->listTitle() ?></h2>
                    <button type="button" id="remarks-dialog-open-button"><?= $view->getRemarksButtonText() ?></button>
                    <button type="button" id="credit-hours-dialog-open-button">Credit Hours</button>
                    <?php if ($view->canShowReport()): ?>
                        <button type="button" id="report-dialog-open-button">View Report</button>
                        <form method="post" action="<?= $view->getMonthReportEmailUrl() ?>">
                            <input type="text" name="mailTo" placeholder="<?= $view->getEmailReportPlaceholder() ?>" required />
                            <input type="hidden" name="month" value="<?= $view->getMonth() ?>" />
                            <input type="hidden" name="year" value="<?= $view->getYear() ?>" />
                            <button type="submit" data-tooltip="Email Report">&#x1F582;</button>
                        </form>
                    <?php endif ?>
                    </h2>
                    <hr />
                    <?php if (count($view->timeEntries) === 0): ?>
                        <p>No activities recorded yet.</p>
                    <?php else: ?>
                        <?php foreach ($view->timeEntries as $entry): ?>
                            <article>
                                <header>
                                    <h3>
                                        Activity on <?= $entry->getDate() ?>
                                        <form data-style="delete-button" method="POST" action="<?= $view->getEntryDeleteUrl($entry) ?>">
                                            <button type="submit" class="danger">X</button>
                                        </form>
                                    </h3>
                                </header>
                                <p>Duration: <?= $entry->getDuration() ?></p>
                                <footer>
                                    <a role="button" href="/time-entry/<?= $entry->getPrimaryKey() ?>">View</a>
                                </footer>
                            </article>
                        <?php endforeach ?>
                    <?php endif ?>
                </article>
                <article data-style="entry-form">
                    <h2><?= $view->getAddActivityFormTitle() ?></h2>
                    <p><span>&#x1F4A1;</span> <?= $view->getAddActivityInstructions() ?></p>
                    <form method="POST" action="/time-entry/add">
                        <div class="grid">
                            <?php foreach ([
                                "month",
                                "dayOfMonth",
                                "year",
                                ] as $inputName): ?>
                            <?= formInput(
                                name: $inputName,
                                label: $view->currentEntry->getLabel($inputName),
                                type: $view->currentEntry->getInputType($inputName),
                                value: $view->currentEntry->$inputName,
                                placeholder: $view->currentEntry->getColumnName($inputName),
                                errorMessage: $view->currentEntry->getFieldErrorMessage($inputName, stringToAppend: " ⚠"),
                                isInvalid: $view->currentEntry->hasError($inputName)
                            )
                            ?>
                            <?php endforeach ?>
                        </div>
                        <div class="grid">
                            <?php foreach ([
                                "hours",
                                "minutes",
                                ] as $inputName): ?>
                            <?= formInput(
                                name: $inputName,
                                label: $view->currentEntry->getLabel($inputName),
                                type: $view->currentEntry->getInputType($inputName),
                                value: $view->currentEntry->$inputName,
                                placeholder: $view->currentEntry->getColumnName($inputName),
                                errorMessage: $view->currentEntry->getFieldErrorMessage($inputName, stringToAppend: " ⚠"),
                                isInvalid: $view->currentEntry->hasError($inputName)
                            )
                            ?>
                            <?php endforeach ?>
                        </div>
                        <?php foreach ($view->currentEntry as $field => $value): ?>
                            <?php $inputType = $view->currentEntry->getInputType($field); ?>
                            <?php if ($inputType === InputTypes::Hidden): ?>
                                <input type="<?= $inputType->asString() ?>"
                                    id="<?= $field ?>"
                                    name="<?= $field ?>"
                                    value="<?= $value instanceof DateTimeImmutable ? $value->format(DATE_RSS) : $value ?? TimeEntry::getDefaultValue($field) ?>" />
                            <?php endif ?>
                        <?php endforeach ?>
                        <?php if ($view->hasFilter()): ?>
                            <input type="hidden" id="filterYear" name="filterYear" value="<?= $view->getYearFilter() ?>" />
                            <input type="hidden" id="filterMonth" name="filterMonth" value="<?= $view->getMonthFilter() ?>" />
                        <?php endif ?>
                        <div class="grid">
                            <input type="reset">
                            <input type="submit" value="Submit">
                        </div>
                    </form>
                </article>
            </div>
        </main>
        <footer class="container">Version <?= $view->appVersion ?></footer>
        <dialog id="remarks-dialog" aria-labelledby="remarks-dialog-title" aria-describedby="remarks-dialog-description">
            <article>
                <header>
                    <button type="button" id="remarks-dialog-close-button" class="close" aria-label="Close" rel="prev"></button>
                    <p>&#x1F4D8; <strong>Remarks</strong></p>
                </header>
                <form method="post" action="/remarks-for-month">
                    <?php if ($view->isEditingRemarks()): ?>
                        <input type="hidden" id="remarks-id" name="id" value="<?= $view->getRemarksId() ?>" />
                    <?php endif ?>
                    <input type="hidden" id="remarks-tenant-id" name="tenantId" value="<?= $view->tenantId ?>" />
                    <input type="hidden" id="remarks-month" name="month" value="<?= $view->getRemarksMonth() ?>" />
                    <input type="hidden" id="remarks-year" name="year" value="<?= $view->getRemarksYear() ?>" />
                    <?php if ($view->hasFilter()): ?>
                        <input type="hidden" id="filterYear" name="filterYear" value="<?= $view->getYearFilter() ?>" />
                        <input type="hidden" id="filterMonth" name="filterMonth" value="<?= $view->getMonthFilter() ?>" />
                    <?php endif ?>
                    <textarea
                        id="remarks"
                        name="remarks"
                        rows="6"
                        cols="50"
                        maxlength="<?= 0x1000 ?>"
                        placeholder="Add remarks here..."><?= $view->getRemarksForCurrentMonth() ?></textarea>
                    <button type="submit">Save</button>
                </form>
            </article>
        </dialog>
        <dialog id="report-dialog">
            <article>
                <header>
                    <button type="button" id="report-dialog-close-button" class="close" aria-label="Close" rel="prev"></button>
                    <p>Report for <?= $view->getMonthTitle() ?></p>
                </header>
                <p>
                    <strong>Total: <?= $view->getTotalHours() ?> Hours</strong>
                </p>
                <?php if ($view->shouldShowCreditHours()): ?>
                    <p>
                        <strong>Credit: <?= $view->getCreditHours() ?> Hours</strong>
                    </p>
                <?php endif ?>
                <form method="get" action="#">
                    <label for="report-remarks">Remarks</label>
                    <textarea
                        readonly
                        id="report-remarks"
                        name="remarks"
                        rows="6"
                        cols="50"><?= $view->getRemarksForCurrentMonth() ?></textarea>
                </form>
            </article>
        </dialog>
        <dialog id="credit-hours-dialog">
            <article>
                <header>
                    <h2>
                        <button type="button" id="credit-hours-dialog-close-button" class="close" aria-label="Close" rel="prev"></button>
                        <p>Credit Hours</p>
                    </h2>
                </header>
                <form method="post" action="/credit-hours">
                    <label for="credit-hours">Hours</label>
                    <input type="number" id="credit-hours" name="hours" min="0" value="<?= $view->getCreditHours() ?>" />
                    <input type="hidden" id="remarks-tenant-id" name="tenantId" value="<?= $view->tenantId ?>" />
                    <input type="hidden" id="credit-hours-month" name="month" value="<?= $view->getRemarksMonth() ?>" />
                    <input type="hidden" id="credit-hours-year" name="year" value="<?= $view->getRemarksYear() ?>" />
                    <?php if ($view->hasFilter()): ?>
                        <input type="hidden" id="filterYear" name="filterYear" value="<?= $view->getYearFilter() ?>" />
                        <input type="hidden" id="filterMonth" name="filterMonth" value="<?= $view->getMonthFilter() ?>" />
                    <?php endif ?>
                    <button type="submit">Save</button>
                </form>
            </article>
        </dialog>
        <dialog id="profile-dialog">
            <article>
                <header>
                    <button type="button" id="profile-dialog-close-button" class="close" aria-label="Close" rel="prev"></button>
                    <p><strong>Manage Profile</strong></p>
                </header>
                <h4><?= $view->user->name ?></h4>
                <nav>
                    <ul>
                        <li>
                            <a href="/logout" tabindex="0">Logout</a>
                        </li>
                    </ul>
                </nav>
                <p>
                    Your profile data must be edited with your authentication provider (i.e. Google, Apple, etc).
                </p>
                <ul>
                    <li>Name: <?= $view->user->name ?></li>
                    <li>Nickname: <?= $view->user->nickname ?></li>
                    <li>Email: <?= $view->user->email ?></li>
                </ul>
                <footer>
                    <a data-style="export-button" target="_blank" href="/export-data" class="secondary" role="button">Export</a>
                    <form data-style="delete-button" method="post" action="/delete-data">
                        <input type="hidden" name="id" value="<?= $view->tenantId ?>" />
                        <button type="submit" class="danger">Purge Data</button>
                    </form>
                </footer>
            </article>
        </dialog>
    </body>

    </html>
<?php
})($this);
