<?php

declare(strict_types=1);

use EricFortmeyer\ActivityLog\UserInterface\Contexts\AccountDeleteSuccessContext;

(function (AccountDeleteSuccessContext $view) {
?>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $view->title ?></title>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml">
        <link rel="stylesheet" href="/resources/css/pico.min.css">
        <link rel="stylesheet" href="/resources/css/overrides.css">
        <meta http-equiv="refresh" content="3; URL=/logout">
    </head>

    <body>
        <main>
            <article>
                <header>
                    <h1><?= $view->title ?></h1>
                </header>
                <p><?= $view->message ?></p>
            </article>
        </main>
    </body>

    </html>
<?php
})($this);
