<?php

declare(strict_types=1);

namespace EricFortmeyer\ActivityLog\config\DiTokens;

const APP_CALLBACK_PATH = "APP_CALLBACK_PATH";
const APP_DB = "APP_DB";
const APP_DB_FILE = "APP_DB_FILE";
const APP_LOGIN_PATH = "APP_LOGIN_PATH";
const APP_LOGOUT_PATH = "APP_LOGOUT_PATH";
const APP_NAME = "APP_NAME";
const APP_REQUEST_TOKEN = "APP_REQUEST_TOKEN";
const AUTH_CLIENT_ID = "AUTH_CLIENT_ID";
const AUTH_CLIENT_SECRET = "AUTH_CLIENT_SECRET";
const AUTH_COOKIE_SECRET = "AUTH_COOKIE_SECRET";
const AUTH_DOMAIN = "AUTH_DOMAIN";
const AUTH_SERVICE = "AUTH_SERVICE";
const BOOTSTRAPPER = "BOOTSTRAPPER";
const CALLBACK_MIDDLEWARE = "CALLBACK_MIDDLEWARE";
const CREDIT_HOURS_CSV_FILE = "CREDIT_HOURS_CSV_FILE";
const CREDIT_HOURS_STORAGE = "CREDIT_HOURS_STORAGE";
const DATA_DIR = "DATA_DIR";
const HASH_KEY = "HASH_KEY";
const LOGIN_MIDDLEWARE = "LOGIN_MIDDLEWARE";
const LOGIN_PASSWD_FILE = "LOGIN_PASSWD_FILE";
const LOGOUT_MIDDLEWARE = "LOGOUT_MIDDLEWARE";
const MAIL_CONFIG = "MAIL_CONFIG";
const REMARKS_CSV_FILE = "REMARKS_CSV_FILE";
const REMARKS_STORAGE = "REMARKS_STORAGE";
const SECRETS_APP_PATH = "SECRETS_APP_PATH";
const SECRETS_BASE_URI = "SECRETS_BASE_URI";
const SECRETS_CLIENT = "SECRETS_CLIENT";
const SECRETS_DIR = "SECRETS_DIR";
const SECRETS_LOGIN_PATH = "SECRETS_LOGIN_PATH";
const SECRETS_SERVICE_HOST = "SECRETS_SERVICE_HOST";
const SECRETS_SERVICE_PORT = "SECRETS_SERVICE_PORT";
const SECRETS_TOKEN_TTL = "SECRETS_TOKEN_TTL";
const SECRETS_VALUE_TTL = "SECRETS_VALUE_TTL";
const TIME_ENTRY_CSV_FILE = "TIME_ENTRY_CSV_FILE";
const TIME_ENTRY_STORAGE = "TIME_ENTRY_STORAGE";
