<?php

declare(strict_types=1);

namespace EricFortmeyer\ActivityLog\DiTokens;

const CREDIT_HOURS_STORAGE = "CREDIT_HOURS_STORAGE";
const CREDIT_HOURS_CSV_FILE = "CREDIT_HOURS_CSV_FILE";
const REMARKS_STORAGE = "REMARKS_STORAGE";
const REMARKS_CSV_FILE = "REMARKS_CSV_FILE";
const TIME_ENTRY_STORAGE = "TIME_ENTRY_STORAGE";
const TIME_ENTRY_CSV_FILE = "TIME_ENTRY_CSV_FILE";
const MAIL_CONFIG = "MAIL_CONFIG";
